Repository Iitpulse/client, pull requests merged in 2022-11, with the labels that each got.

#70 desig, pattern, test, users sidebar etc
  src/App.module.scss
  src/App.tsx
  src/components/Button/Button.module.scss
  src/components/Button/Button.tsx
  src/components/CustomBreadCrumb/CustomBreadCrumb.tsx
  src/components/InputField/InputField.module.scss
  src/components/UserProfile/UserProfile.module.scss
  src/components/UserProfile/UserProfile.tsx
  src/components/index.tsx
  src/layouts/MainLayout.tsx
  src/pages/Batches/Batches.tsx
  src/pages/Home/Home.tsx
  src/pages/Pattern/Pattern.tsx
  src/pages/Questions/Questions.tsx
  src/pages/Result/ResultForAdmin.tsx
  src/pages/Result/ResultForStudent.tsx
  src/pages/Roles/AddNewRole.module.scss
  src/pages/Roles/AddNewRole.tsx
  src/pages/Roles/EditRole/EditRole.module.scss
  src/pages/Roles/EditRole/EditRole.tsx
  src/pages/Roles/Roles.module.scss
  src/pages/Roles/Roles.tsx
  src/pages/Roles/utils.tsx
  src/pages/Test/Test.tsx
  src/pages/Users/Students/Students.tsx
  src/pages/Users/Users.tsx
  src/utils/auth/AuthContext.tsx
  src/utils/contexts/PermissionsContext.tsx
  src/utils/index.ts
Labels: bug, enhancement, ui

#71 breadcrumb fixed and minor changes
  package.json
  src/components/CustomBreadCrumb/CustomBreadCrumb.tsx
  src/pages/Result/Result.module.scss
  src/pages/Result/ResultForStudent.tsx
  src/pages/Roles/Roles.tsx
Labels: refactor-later

#79 question search added
  src/components/InputField/InputField.tsx
  src/pages/DetailedAnalysis/components/Question.tsx
  src/pages/Questions/Questions.tsx
  src/pages/Roles/AddNewRole.tsx
  src/pages/Test/CreateTest.tsx
Labels: enhancement

#87 [Feat]: Migration to vite from webpack
  Dockerfile
  index.html
  package.json
  src/pages/Home/Home.tsx
  src/pages/Users/Students/Students.tsx
  src/utils/api.ts
  src/utils/constants.tsx
  tsconfig.json
  vite.config.ts
Labels: enhancement

#97 [Feat]: Full preview with sidebar done (Create Question)
  src/pages/Questions/CreateQuestion.tsx
  src/pages/Questions/Objective/Objective.tsx
  src/pages/Questions/Questions.tsx
Labels: enhancement, ui
